### ISSUE TITLE
App Deletes My Music

### ISSUE THREAD

**Issue by jnix2** [creati8e/AutoTagger-Issues#1]
I recently updated the app and purchased the add-on features and, since then, the app has been randomly deleting my music after I finish editing their tags. Please fix as it is annoying to have to redownload and redo the tags for songs.

**Comment by creati8e** [comment]
Hi! I am sorry, but i did not enabled notifications and missed your report.
So is this related for songs on SD-card or not?

**Comment by jnix2** [comment]
Hello!

No, the songs are stored on my phone's internal storage.

**Comment by creati8e** [comment]
Got it. That's might be a case when songs are just disappeared from MediaStore. So simple library rescaning fixes it. Are your songs really deleted?

**Comment by jnix2** [comment]
Yes. When the songs are removed from the app, they are also deleted from my
phone's storage.

**Comment by creati8e** [comment]
@jnix2 do you use auto-renaming or batch renaming? I've encountered an issue when track missing for example and filename begins with dot ("."), a file just becames invisible.
I want to believe this is same issue as yours because i know how to fix that.

**Comment by jnix2** [comment]
I have been using the auto-renaming feature.

**Comment by creati8e** [comment]
What pattern do you use?

**Comment by jnix2** [comment]
%Track%. %Title%

**Comment by creati8e** [comment]
Hit! Please see in your folder manager for your "deleted" files. They should be just hidden (enable displaying hidden files before).

**Comment by jnix2** [comment]
That was it, thank you so much!!

**Comment by creati8e** [comment]
Anyway i will fix it! Thank you for participating.

**Comment by creati8e** [comment]
Fixed in v3.0.2
